/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-12-08 07:11:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.UUID;

public final class bxList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.UUID");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    UUID uuid = UUID.randomUUID();
    
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>报销单列表</title>\r\n");
      out.write("\t\t  <!-- plugins:css -->\r\n");
      out.write("  \r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"/jboa/css/commComm.min.css\">\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"/jboa/css/trace.min.css\">\r\n");
      out.write("    <link href=\"/jboa/css/font-awesome.css?v=4.4.0\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <!-- inject:css -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/jboa/css/style.css\">\r\n");
      out.write("  <!-- endinject -->\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/jboa/vendors/iconfonts/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("  \t.page-title{\r\n");
      out.write("  \t\tcolor: red;\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("  </style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"page-header head\">\r\n");
      out.write("\t            <h3 class=\"page-title\">\r\n");
      out.write("\t             <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\r\n");
      out.write("            \t<i class=\"mdi mdi-food\"></i>             \r\n");
      out.write("              </span>          \t          \r\n");
      out.write("              费用报销单\r\n");
      out.write("            </h3>\r\n");
      out.write("            <nav aria-label=\"breadcrumb\">\r\n");
      out.write("              <ol class=\"breadcrumb\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"#\">新增费用报销</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\" aria-current=\"page\">费用报销</li>\r\n");
      out.write("              </ol>\r\n");
      out.write("            </nav>\r\n");
      out.write("          </div>\r\n");
      out.write("       <!--内容-->\r\n");
      out.write("       <div>\r\n");
      out.write("       \t<div style=\"margin-left:30px ;\">\r\n");
      out.write("       \t\t<button class=\"btn btn-primary btn-default\" type=\"button\" name=\"tj\"><i class=\"fa fa-check\"></i>&nbsp;提交</button>\r\n");
      out.write("       \t\t<button class=\"btn btn-warning btn-default\" type=\"button\" name=\"bc\"><i class=\"fa fa-save\"></i>&nbsp;&nbsp;<span class=\"bold\">保存</span>  </button>\r\n");
      out.write("       \t\t<button class=\"btn btn-danger btn-default\" type=\"button\"><i class=\"fa fa-backward\"></i>&nbsp;&nbsp;<span class=\"bold\">返回</span>  </button>\r\n");
      out.write("       \t\t\r\n");
      out.write("       \t</div>\r\n");
      out.write("       \t\t<div>\r\n");
      out.write("       \t\t\t<table>\r\n");
      out.write("                                    <!--查看正文-->\r\n");
      out.write("                                    <!-- ngIf: normalCondition() && (formModel.showWordHtmlContent || formModel.showPDFFlg || formModel.xlsFileFlg) -->\r\n");
      out.write("                                    <div class=\"htmlPadding\" id=\"htmlPadding\">\r\n");
      out.write("                                        <form id=\"templateContent\" name=\"templateContent\" class=\"text-left ng-pristine ng-valid\">\r\n");
      out.write("                                            <div random-code=\"6B3A6735DB\" id=\"6B3A6735DB\">\r\n");
      out.write("                                                <div data-ng-init=\"loadPageToInitScroll()\" id=\"contentTrace\" ng-bind-html=\"formModel.contentMemo|to_trusted\" class=\"ng-binding\"><center>\r\n");
      out.write("<table width=\"720\" height=\"\" align=\"center\" bordercolor=\"#000000\" style=\"border-collapse: separate;\" bgcolor=\"#ffffff\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"50\" align=\"center\" style=\"border-color: rgb(0, 0, 0);\" bgcolor=\"\" colspan=\"4\">\r\n");
      out.write("<span style=\"font-size: 23pt;\">\r\n");
      out.write("<font color=\"#000000\">\r\n");
      out.write("费用报销单\r\n");
      out.write("</font>\r\n");
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=\"60\" height=\"35\" style=\"border-color: rgb(0, 0, 0);\" bgcolor=\"\">流水号：</td>\r\n");
      out.write("<td height=\"20\" style=\"border-color: rgb(0, 0, 0);\">\r\n");
      out.write("<input name=\"流水号\" title=\"流水号\" class=\"InputStyle_Edit\" id=\"MAFO_3\" datafld=\"SYS_SEL_AUTONUM\" value=\"流水号{自动流水号}\" manydictnum=\"0\" tempforautonum=\"\" fieldtype=\"2\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"lsh\" relation=\"\" sql=\"0\" type=\"hidden\" oldvalue=\"\"><span id=\"MAFO_3_6B3A6735DB\" elname=\"流水号\" datafld=\"SYS_SEL_AUTONUM\" style=\"\" fieldid=\"TraceD0018866EPJ\" randomcode=\"6B3A6735DB\" template=\"829c365f5c134c6eb8bbd0f3\">BMYS_20181127011</span>\r\n");
      out.write("</td>\r\n");
      out.write("<td width=\"80\" height=\"20\" align=\"center\" style=\"border-color: rgb(0, 0, 0);\" bgcolor=\"\">申请日期</td>\r\n");
      out.write("<td width=\"150\" height=\"20\" align=\"center\" style=\"border-color: rgb(0, 0, 0);\" bgcolor=\"\">\r\n");
      out.write("<input name=\"申请日期\" title=\"申请日期\" class=\"InputStyle_Edit\" id=\"MAFO_4\" datafld=\"SYS_SEL_DATE\" value=\"申请日期{日期选择}\" manydictnum=\"\" tempforautonum=\"\" fieldtype=\"3\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"sqrq\" relation=\"\" sql=\"\" showstyle=\"yyyy-MM-dd\" type=\"hidden\" oldvalue=\"\"><span id=\"MAFO_4_6B3A6735DB\" elname=\"申请日期\" datafld=\"SYS_SEL_DATE\" style=\"\" fieldid=\"TraceD001895UF48\" randomcode=\"6B3A6735DB\">2018-11-27</span>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("<table width=\"720\" height=\"\" align=\"center\" bordercolor=\"#000000\" style=\"border-style: solid; border-collapse: collapse;\" bgcolor=\"#ffffff\" border=\"1\" cellspacing=\"0\" cellpadding=\"1\">\r\n");
      out.write("<tbody>\r\n");
      out.write("<tr>\r\n");
      out.write("<td width=\"100\" height=\"35\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">申请部门</td>\r\n");
      out.write("<td width=\"150\" height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">\r\n");
      out.write("<input name=\"申请部门\" title=\"申请部门\" class=\"InputStyle_Edit\" id=\"MAFO_1\" datafld=\"SYS_SEL_CREATERDEPT\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" manydictnum=\"\" tempforautonum=\"\" fieldtype=\"2\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"sqbm\" relation=\"\" sql=\"\" type=\"hidden\" oldvalue=\"\"><span id=\"MAFO_1_6B3A6735DB\" elname=\"申请部门\" datafld=\"SYS_SEL_CREATERDEPT\" style=\"\" fieldid=\"TraceD001893V5O6\" randomcode=\"6B3A6735DB\" memo=\"ROOT\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("<td width=\"100\" height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">申请人</td>\r\n");
      out.write("<td width=\"120\" height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">\r\n");
      out.write("<input name=\"申请人\" title=\"申请人\" class=\"InputStyle_Edit\" id=\"MAFO_2\" datafld=\"SYS_SEL_CREATERNAME\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" manydictnum=\"\" tempforautonum=\"\" fieldtype=\"2\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"sqr\" relation=\"\" sql=\"\" type=\"hidden\" oldvalue=\"\"><span id=\"MAFO_2_6B3A6735DB\" elname=\"申请人\" datafld=\"SYS_SEL_CREATERNAME\" style=\"\" fieldid=\"TraceD001891NU6B\" randomcode=\"6B3A6735DB\" memo=\"user\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td width=\"100\" height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">总金额</td>\r\n");
      out.write("<td width=\"150\" height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">\r\n");
      out.write("<input name=\"总金额\" title=\"总金额\" class=\"InputStyle_Edit\" id=\"MAFO_5\" datafld=\"SYS_SEL_DATE\" value=\"\" manydictnum=\"\" tempforautonum=\"\" fieldtype=\"3\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"ysyf\" relation=\"\" sql=\"\"  type=\"hidden\" oldvalue=\"\"><table cellspacing=\"0\" cellpadding=\"0\" id=\"MAFO_5_6B3A6735DB_table\"><tbody><tr><td>\r\n");
      out.write("\t<div class=\"template_date_show_div\" style=\"min-width:108px\">\r\n");
      out.write("\t\t<input datafld=\"SYS_SEL_DATE\" type=\"text\" class=\"template_date_input\" onfocus=\"this.select();\" elname=\"总金额\" id=\"MAFO_5_6B3A6735DB\" style=\"width:108px;height: 23px\" fieldid=\"TraceD001889CG61\" randomcode=\"6B3A6735DB\"></div></td></tr></tbody></table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\" colspan=\"6\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"template_table_default_color\" id=\"list_table_0\" cellspacing=\"0\" cellpadding=\"1\" width=\"100%\"><tbody rowmax=\"9\" datanum=\"9\" deltbl=\"\" newtablename=\"htoa_yssq_mxb\" id=\"ListTable_0\" titlestr=\";预算费用项目;金额;用途说明;\">\r\n");
      out.write("\t<tr id=\"tableTitle_0\" height=\"30\">\r\n");
      out.write("\t\t<td tabletitle=\"预算费用项目\" width=\"120\" style=\";text-align:center;color:#696969;font-size:10pt;text-align:center;border-width:1px;border-color:#B2B2B2;border-style:solid;background-color:#ECECEC;\">预算费用项目</td>\r\n");
      out.write("\t\t<td tabletitle=\"金额\" width=\"100\" style=\";text-align:center;color:#696969;font-size:10pt;text-align:center;border-width:1px;border-color:#B2B2B2;border-style:solid;background-color:#ECECEC;\">金额</td>\t\r\n");
      out.write("\t\t<td tabletitle=\"用途说明\" width=\"250\" style=\";text-align:center;color:#696969;font-size:10pt;text-align:center;border-width:1px;border-color:#B2B2B2;border-style:solid;background-color:#ECECEC;\">用途说明</td>\r\n");
      out.write("\t\t<td tabletitle=\"凭据截图\" width=\"150\" style=\";text-align:center;color:#696969;font-size:10pt;text-align:center;border-width:1px;border-color:#B2B2B2;border-style:solid;background-color:#ECECEC;\">凭据截图</td>\r\n");
      out.write("\t\t<td align=\"center\" width=\"40\" style=\"color: rgb(105, 105, 105); font-size: 10pt; text-align: center; border-width: 1px; border-color: rgb(178, 178, 178); border-style: solid; background-color: rgb(236, 236, 236); cursor: pointer;\">\r\n");
      out.write("\t\t\t<table width=\"40\">\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"24\"><span name=\"add\" rowid=\"ListTable_0_1\" class=\"template_list_add\" tablename=\"htoa_yssq_mxb\"></span></td>\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t</tbody>\r\n");
      out.write("\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"80\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">事由</td>\r\n");
      out.write("<td height=\"20\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\" colspan=\"5\">\r\n");
      out.write("<input name=\"事由\" title=\"事由\" class=\"InputStyle_Edit\" id=\"MAFO_7\" datafld=\"SYS_SEL_CUPDTRACEMIND\" style=\"width: 98%; height: 69px;\" value=\"事由{原因}\" manydictnum=\"\" tempforautonum=\"\" fieldtype=\"5\" fieldlength=\"255\" defaultshowvalue=\"\" fieldtitle=\"zjl\" relation=\"\" sql=\";imgName;date;\" showstyle=\"\" showlast=\"false\" fielduse=\"\" fieldhide=\"\" defaulttruevalue=\"\" type=\"hidden\" oldvalue=\"\">\r\n");
      out.write("\t<div elname=\"事由\" datafld=\"SYS_SEL_CUPDTRACEMIND\" showtype=\";imgName;date;\" showstyle=\"\" divstyle=\"\" style=\";height:99%;\" fieldid=\"TraceD0018878JUQ\" randomcode=\"6B3A6735DB\">\r\n");
      out.write("\t\t<textarea style=\"border: 0px;width: 617px;height: 77px;\" class=\"cn_sy\"></textarea>\r\n");
      out.write("\t</div>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td height=\"60\" align=\"center\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" bgcolor=\"\">流程说明</td>\r\n");
      out.write("<td height=\"20\" style=\"border-style: solid; border-color: rgb(0, 0, 0);\" colspan=\"5\">\r\n");
      out.write("申请流程：\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("申请人\r\n");
      out.write("<font color=\"#7f7f7f\">\r\n");
      out.write("→经理→总经理→财务\r\n");
      out.write("</font>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("<textarea name=\"javascript\" style=\"display: none\"></textarea></div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                           \r\n");
      out.write("       \t\t\t</table>    \t\t\t\r\n");
      out.write("       \t\t</div>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/jboa/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(\"[name=add]\").click(function(){\r\n");
      out.write("\t\t\tvar app=\"<tr id='ListTable_0_6' rownumber='6' height='50' rowindex='6' class='zj'>\"+\r\n");
      out.write("\t\t\t\t\t\"<td style='color:#696969;border-width:1px;border-color:#B2B2B2;border-style:solid;;text-align:center;background-color: rgb(250, 255, 189) '>\"+\r\n");
      out.write("\t\t\t\t\t\"<input id='LISTFO_费用项目_6_6B3A6735DB' elname='费用项目_6' datafld='TEXT' style='border:1px solid #ccc; height:41px;color:#696969;background-color: rgb(250, 255, 189)' class='template_input_focus_style cost' title='费用项目' listtablename='htoa_yssq_mxb' rowindex='6' fieldid='TraceD0018972ACC' randomcode='6B3A6735DB'>\"+\r\n");
      out.write("\t\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\t\"<td style='color:#696969;border-width:1px;border-color:#B2B2B2;border-style:solid;;text-align:center;background-color: rgb(250, 255, 189)'>\"+\r\n");
      out.write("\t\t\t\t\"<input id='LISTFO_金额_6_6B3A6735DB' elname='金额_6' datafld='TEXT' style='border:1px solid #ccc;height:41px;color:#696969;background-color: rgb(250, 255, 189)' class='template_input_focus_style cn_money' title='金额' listtablename='htoa_yssq_mxb' rowindex='6' fieldid='TraceD0018972ACC' randomcode='6B3A6735DB'>\"+\r\n");
      out.write("\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\t\"<td style='color:#696969;border-width:1px;border-color:#B2B2B2;border-style:solid;;text-align:left;background-color: rgb(250, 255, 189)'>\"+\t\t\t\r\n");
      out.write("\t\t\t\t\"<input id='LISTFO_用途说明_6_6B3A6735DB' elname='用途说明_6' datafld='TEXT' style='border:1px solid #ccc;height:41px;color:#696969;background-color: rgb(250, 255, 189)' class='template_input_focus_style cn_use' title='用途说明' listtablename='htoa_yssq_mxb' rowindex='6' fieldid='TraceD0018962818' randomcode='6B3A6735DB'>\"+\t\r\n");
      out.write("\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\"<td  style='color:#696969;border-width:1px;border-color:#B2B2B2;border-style:solid;;text-align:center;background-color: rgb(250, 255, 189)'>\"+\t\r\n");
      out.write("\t\t\t\"<input id='LISTFO_凭据截图_6_6B3A6735DB' style='height:41px;color:#696969;background-color: rgb(250, 255, 189)' class='template_input_focus_style photoshow' title='凭据截图' rowindex='6' listtablename='htoa_yssq_mxb' fieldid='TraceD0018972ACC' randomcode='6B3A6735DB' type='file'>\"+\r\n");
      out.write("\t\t\t\"<img style='dispaly:none;' im='' ds=''/>\"+\r\n");
      out.write("\t\t\t\"</td>\"+\t\t\t\r\n");
      out.write("\t\t\"<td align='center' width='40' style='color:#696969;border-width:1px;border-color:#B2B2B2;border-style:solid;'><table width='40'><tbody>\"+\t\t\r\n");
      out.write("\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\"<td id='deltd' style='text-align: center' width='16'>\"+\r\n");
      out.write("\t\t\t\"<span name='del' rowid='ListTable_0_6' class='template_list_del' tablename='htoa_yssq_mxb'></span></td></tr></tbody></table></td>\"+\r\n");
      out.write("\t\t\t\"</tr>\"; \r\n");
      out.write("\t\t\t$(\"#tableTitle_0\").after(app);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).on(\"click\",\"[name=del]\",function(){\r\n");
      out.write("\t\t\t$(this).parents(\".zj\").remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t//data:base64数据       name:文件名(feng.jpg)\r\n");
      out.write("\t\t/* var imgObj1 = {\r\n");
      out.write("\t\t\"data\" : \"[]\",\r\n");
      out.write("\t\t\"name\" : \"[]\"\r\n");
      out.write("\t\t};//图片对象 */\r\n");
      out.write("\t//\tde+=\"{\\\"subtotal\\\":\\\"\"+$(\".cn_money\").val()+\"\\\",\\\"desc\\\":\\\"\"+$(\".cn_use\").val()+\"\\\"},\";\t\t\t\r\n");
      out.write("\t\tvar imgobj=\"\";\r\n");
      out.write("\t \tvar data=\"\";\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t//选择预览图片\t\t\r\n");
      out.write("\t\t$(document).on(\r\n");
      out.write("\t\t\t\t\"change\",\r\n");
      out.write("\t\t\t\t\t\".photoshow\",\r\n");
      out.write("\t\t\t\tfunction(e) {\r\n");
      out.write("\t\t\t\t\tvar xx=$(this);\r\n");
      out.write("\t\t\t\t\txx.hide();\r\n");
      out.write("\t\t\t\t\t var fr = new FileReader();//读取文件\r\n");
      out.write("\t\t\t\t\tvar file = this.files[0];//选择第一个文件 \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\txx.next().show();\r\n");
      out.write("\t\t\t\t\tvar _temp = file.name.match(/\\.jpg|\\.png|\\.gif|\\.bmp/i);\r\n");
      out.write("\t\t\t\t\tif (!_temp) {\r\n");
      out.write("\t\t\t\t\t\tthis.value = \"\";\r\n");
      out.write("\t\t\t\t\t\talert(\"目前只支持jpg,png,bmp,gif格式图片文件\");\r\n");
      out.write("\t\t\t\t\t\txx.show();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t} else if (file.size > (10*1024 * 1024)) {\r\n");
      out.write("\t\t\t\t\t\tthis.value = \"\";\r\n");
      out.write("\t\t\t\t\t\talert(\"目前只支持小于1M大小图片文件\");\r\n");
      out.write("\t\t\t\t\t\txx.show();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfr.readAsDataURL(file);//读取文件\r\n");
      out.write("\t\t\t\t\t//操作文件事件\r\n");
      out.write("\t\t\t\t\tfr.onload = function() {\r\n");
      out.write("\t\t\t\t\t\tvar base64Data = this.result;//获得base编码字符串格式\r\n");
      out.write("\t\t\t\t\t\t/* \r\n");
      out.write("\t\t\t\t\t\t\tdata= base64Data.substring(base64Data\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t.indexOf(';base64,') + 8); *///设置base64数据字符串 */\r\n");
      out.write("\t\t\t\t\t\t\t\txx.next().show();\r\n");
      out.write("\t\t\t\t\t\t\t\txx.next().css({\"height\":\"41px\",\"width\":\"60px\",\"text-align\":\"center\"});\r\n");
      out.write("\t\t\t\t\t\txx.next().attr(\"src\", base64Data);//显示图片\r\n");
      out.write("\t\t\t\t\t\txx.next().attr(\"im\",file.name);\r\n");
      out.write("\t\t\t\t\t\txx.next().attr(\"ds\", base64Data.substring(base64Data\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t.indexOf(';base64,') + 8));\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t//通用新增方法\r\n");
      out.write("\t\tfunction add(num){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar re={};\r\n");
      out.write("\t\t\tre[\"createman\"]=$(\"#MAFO_2\").val();\r\n");
      out.write("\t\t\tre[\"departmentid\"]=$(\"#MAFO_1\").val();\r\n");
      out.write("\t\t\tre[\"nextdealman\"]=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.pid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\tre[\"event\"]=$(\".cn_sy\").val();\r\n");
      out.write("\t\t \tre[\"totalcount\"]=$(\".cn_money\").val(); \r\n");
      out.write("\t\t\t\tif(num==\"2\"){\r\n");
      out.write("\t\t\t\t\tre[\"statusid\"]=2;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\tif(num==\"1\"){\r\n");
      out.write("\t\t\t\t\tre[\"statusid\"]=1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar abc=0;\t\r\n");
      out.write("\t\t\tre[\"details\"]=[]\r\n");
      out.write(" \t\t\t$(\".zj\").each(function(){\t\t\t\r\n");
      out.write(" \t\t\t\tvar detail={};\r\n");
      out.write(" \t\t\t\tdetail[\"subtotal\"]=$(this).find($(\".cn_money\")).val();\r\n");
      out.write(" \t\t\t\tdetail[\"desc\"]=$(this).find($(\".cn_use\")).val();\r\n");
      out.write(" \t\t\t\tdetail[\"pictruename\"]=$(this).find('img').attr(\"im\")\r\n");
      out.write(" \t\t\t\tdetail[\"pictruepath\"]=$(this).find('img').attr(\"ds\");\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\t\t\tre.details[abc]=detail;\r\n");
      out.write(" \t\t\t\tabc++;\r\n");
      out.write(" \t\t\t})\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t\t\t$.ajax(\"/jboa/remburse/addRemburse\", {\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tcontentType:\"application/json\",//非常重要\r\n");
      out.write("\t\t\t\tdata:JSON.stringify(re),//非常重要\r\n");
      out.write("\t\t\t\ttimeout : 5000,\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data.code == 200) {\r\n");
      out.write("\t\t\t\t\t\talert(\"保存成功\");\r\n");
      out.write("\t\t\t\t\t\tlocation.href = '/jboa/remburse/querylist';\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"保存失败\");\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//点击提交按钮\r\n");
      out.write("\t\t$(document).on(\"click\",\"[name=tj]\",function(){\r\n");
      out.write("\t\t\tadd(\"2\");\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t//点击保存按钮\r\n");
      out.write("\t\t$(document).on(\"click\",\"[name=bc]\",function(){\r\n");
      out.write("\t\t\t add(\"1\"); \r\n");
      out.write("\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
