/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-12-08 06:06:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<!-- Required meta tags -->\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t<title>清泉办公管理系统</title>\r\n");
      out.write("\t\t<!-- plugins:css -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/vendors/iconfonts/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- inject:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/css/style.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"/jboa/images/logo.jpg\" />\r\n");
      out.write("\t\t <link href=\"/jboa/css/query/style.css?v=4.1.0\" rel=\"stylesheet\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.cn_ld .label{\r\n");
      out.write("\t\t\tline-height: 12px;\r\n");
      out.write("   \t\t\t padding: 1px 5px;\r\n");
      out.write("    \t\tposition: absolute;\r\n");
      out.write("   \t\t\t right: 0px;\r\n");
      out.write("    \t\ttop: 12px;\t\r\n");
      out.write("    \t\tleft: 6px;\r\n");
      out.write("    \t \tborder-radius: 50%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.nav-link .label{\r\n");
      out.write("\t\t\t    display: inline;\r\n");
      out.write("    \t\t\tpadding: .2em .6em .3em;\r\n");
      out.write("    \t\t\tfont-size: 75%;\r\n");
      out.write("    \t\t\tfont-weight: 700;\r\n");
      out.write("    \t\t\tline-height: 1;\r\n");
      out.write("    \t\t\tcolor: #fff;\r\n");
      out.write("    \t\t\ttext-align: center;\r\n");
      out.write("   \t\t\t\twhite-space: nowrap;\r\n");
      out.write("   \t\t\t\tvertical-align: baseline;\r\n");
      out.write("    \t\t\tborder-radius: 50%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div class=\"container-scroller\">\r\n");
      out.write("\t\t\t<!-- partial:partials/_navbar.html -->\r\n");
      out.write("\t\t\t<nav class=\"navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t<img class=\"brand-logo\" src=\"/jboa/images/bitbug_favicon.ico\" alt=\"logo\" width=\"32\" height=\"32\" />\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" style=\"width: 200px;\" href=\"index.html\">清泉办公管理系统</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"navbar-menu-wrapper d-flex align-items-stretch\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav navbar-nav-right\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item nav-profile dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" id=\"profileDropdown\" href=\"#\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"nav-profile-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/jboa/images/faces/face1.jpg\" alt=\"image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"availability-status online\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"nav-profile-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-1 text-black\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu navbar-dropdown\" aria-labelledby=\"profileDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/jboa/login.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-cached mr-2 text-success\"></i> 切换用户\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/jboa/login.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-logout mr-2 text-primary\"></i> 退出登陆\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item d-none d-lg-block full-screen-link\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-fullscreen\" id=\"fullscreen-button\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<a style=\"width: 30px;\" class=\"nav-link count-indicator dropdown-toggle cn_ld\" id=\"notificationDropdown\" href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-bell-outline\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-danger\" id=\"cn_msg\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--通知红点-->\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"notificationDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"p-3 mb-0\">通知栏</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item preview-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"preview-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"preview-icon bg-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"mdi mdi-calendar\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"preview-item-content d-flex align-items-start flex-column justify-content-center\" id=\"cn_message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"preview-subject font-weight-normal mb-1\">请假申请</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"text-gray ellipsis mb-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"p-3 mb-0 text-center\">my mailbox</h6>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"offcanvas\">\r\n");
      out.write("          <span class=\"mdi mdi-menu\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t<div class=\"container-fluid page-body-wrapper\">\r\n");
      out.write("\t\t\t\t<!-- partial:partials/_sidebar.html -->\r\n");
      out.write("\t\t\t\t<nav class=\"sidebar sidebar-offcanvas\" id=\"sidebar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item nav-profile\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"nav-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"nav-profile-image\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"/jboa/images/faces/face1.jpg\" alt=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"login-status online\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--change to offline or busy as needed-->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"nav-profile-text d-flex flex-column\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"font-weight-bold mb-2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"text-danger text-small\" style=\"color:#fe7c7c66\">部门:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"text-danger text-small\" style=\"margin-top:5px;color:#fe7c7c66\">职位:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.position.positionname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-bookmark-check text-success nav-profile-badge\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"JavaScript:void(0);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-title\"  onclick=\"Switch(this)\">首页</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-home menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" data-toggle=\"collapse\" href=\"#ui-bill\" aria-expanded=\"false\" aria-controls=\"ui-bill\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-title\">报销单管理</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-food menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse\" id=\"ui-bill\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link cn_addbx\" url=\"bxList.jsp\" onclick=\"Switch(this)\">新增报销单</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" url=\"/jboa/remburse/querylist\" onclick=\"Switch(this)\">查看报销单</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" data-toggle=\"collapse\" href=\"#ui-leave\" aria-expanded=\"false\" aria-controls=\"ui-leave\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-title\">请假管理</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-run menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse\" id=\"ui-leave\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"javascript:void(0)\" onclick=\"Switch(this)\">请假</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"javascript:void(0)\" onclick=\"Switch(this)\">查看请假</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" data-toggle=\"collapse\" href=\"#ui-statistics\" aria-expanded=\"false\" aria-controls=\"ui-statistics\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-title\">统计报表</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-file-chart  menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse\" id=\"ui-statistics\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"javascript:void(0)\" onclick=\"Switch(this)\">报销单月度统计</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"javascript:void(0)\" onclick=\"Switch(this)\">报销单年度统计</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"nav-link\" data-toggle=\"collapse\" href=\"#ui-message\" aria-expanded=\"false\" aria-controls=\"ui-message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"menu-title\">信息中心</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <span class=\"label label-danger\">16</span> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"menu-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"mdi mdi-message-processing menu-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"collapse\" id=\"ui-message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"nav flex-column sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"nav-link\"  url=\"/jboa/leave/queryMessage?pageNum=1&addressees_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"Switch(this)\">信息收件箱</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t\t<div class=\"main-panel\">\r\n");
      out.write("\t\t\t\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<iframe id=\"iframe\" src=\"pages/show/show.jsp\" style=\"overflow: visible;\" scrolling=\"yes\" frameborder=\"no\" width=\"100%\" height=\"1000\">\r\n");
      out.write("          \t\r\n");
      out.write("          </iframe>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- content-wrapper ends -->\r\n");
      out.write("\t\t\t\t\t<!-- partial:partials/_footer.html -->\r\n");
      out.write("\t\t\t\t\t<footer class=\"footer\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2099 <a href=\"\" target=\"_blank\">BootstrapDash</a>. All rights reserved. </span>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">Hand-crafted & made with\r\n");
      out.write("              <i class=\"mdi mdi-heart text-danger\"></i> - More Templates <span style=\"color: #1bcfb4;\">研发二部</span> - -<i class=\"mdi mdi-heart text-danger\"></i>曹娜<i class=\"mdi mdi-heart text-danger\"></i> </span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</footer>\r\n");
      out.write("\t\t\t\t\t<!-- partial -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- main-panel ends -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- page-body-wrapper ends -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- container-scroller -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- plugins:js -->\r\n");
      out.write("\t\t<script src=\"/jboa/vendors/js/vendor.bundle.base.js\"></script>\r\n");
      out.write("\t\t<script src=\"/jboa/vendors/js/vendor.bundle.addons.js\"></script>\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- Plugin js for this page-->\r\n");
      out.write("\t\t<!-- End plugin js for this page-->\r\n");
      out.write("\t\t<!-- inject:js -->\r\n");
      out.write("\t\t<script src=\"/jboa/js/off-canvas.js\"></script>\r\n");
      out.write("\t\t<script src=\"/jboa/js/misc.js\"></script>\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- Custom js for this page-->\r\n");
      out.write("\t\t<script src=\"/jboa/js/dashboard.js\"></script>\r\n");
      out.write("\t\t<!-- End custom js for this page-->\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script src=\"/jboa/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction Switch(site) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tswitch($(site).text()) {\r\n");
      out.write("\t\t\t\tcase \"首页\":\r\n");
      out.write("\t\t\t\t$(\"#iframe\").attr(\"src\",\"pages/show/show.jsp\");\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"新增报销单\":\r\n");
      out.write("\t\t\t\t\tvar url=$(site).attr(\"url\");\r\n");
      out.write("\t\t\t\t\t$(\".content-wrapper iframe\").attr(\"src\",url);\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"查看报销单\":\r\n");
      out.write("\t\t\t\t\t\tvar url=$(site).attr(\"url\");\r\n");
      out.write("\t\t\t\t\t$(\".content-wrapper iframe\").attr(\"src\",url);\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"请假\":\r\n");
      out.write("\t\t\t\t\t$(\"#iframe\").attr(\"src\",\"pages/show/leave.jsp\");\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"查看请假\":\r\n");
      out.write("\t\t\t\t\t$(\"#iframe\").attr(\"src\",\"/jboa/leave/queryLeave?pageNum=1&positionid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.position.positionid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&departmentid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&employeeid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\t\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"报销单月度统计\":\r\n");
      out.write("\t\t\t\t\t$(\"#iframe\").attr(\"src\",\"pages/show/monthlyStatistics.jsp\");\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"报销单年度统计\":\r\n");
      out.write("\t\t\t\t\t\t$(\"#iframe\").attr(\"src\",\"pages/show/yearlyStatistics.jsp\");\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"信息收件箱\":\r\n");
      out.write("\t\t\t\t\tvar url=$(site).attr(\"url\");\r\n");
      out.write("\t\t\t\t\t$(\".content-wrapper iframe\").attr(\"src\",url);\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write(" </script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\tvar count = 0;\r\n");
      out.write("\t//ajax轮询消息\r\n");
      out.write("\twindow.setInterval(Message,4000); \r\n");
      out.write("\t\r\n");
      out.write("    function Message() {\r\n");
      out.write("    \tcount = 0;\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#cn_message\").html(\"\");\r\n");
      out.write("    \t\r\n");
      out.write("    \t$.post(\"/jboa/leave/queryMessageAjax\",{\"addressees_id\":");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\"pageNum\":1},function(res){\r\n");
      out.write("    \t\t$.each(res.list,function(i,data){\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\t\tcount++;\r\n");
      out.write("    \t\t\t\t/* 消息数量 */\r\n");
      out.write("    \t\t\t\t$(\"#cn_msg\").text(count);\r\n");
      out.write("    \t\t\t\t/* 提示内容信息 */\r\n");
      out.write("    \t\t\t\tvar ht = \"\";\r\n");
      out.write("    \t\t\t\t\t//请假\r\n");
      out.write("    \t\t\t\t\tif(data.type_id==1){\r\n");
      out.write("    \t\t\t\t\t\tvar message = \"<h6 class=\\\"preview-subject font-weight-normal mb-1\\\">\"+data.addresserName+\"申请请假</h6>\";\r\n");
      out.write("    \t\t\t\t\t\tif(data.message_sta==2){\r\n");
      out.write("    \t\t\t\t\t\t\tmessage = \"<h6 class=\\\"preview-subject font-weight-normal mb-1\\\">您申请的请假,\"+data.addresserName+\"已审批</h6>\";\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\tht = \"<div class=\\\"dropdown-divider\\\"></div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<a href='javascript:void(0)' onclick='Sw(\"+data.type_id+\",\"+data.message_sta+\",\"+data.biz_id+\")' name='查看请假' class=\\\"dropdown-item preview-item\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-thumbnail\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-icon bg-success\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"\t<i class=\\\"mdi mdi-run\\\"></i>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-item-content d-flex align-items-start flex-column justify-content-center\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmessage+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t<p class=\\\"text-gray mb-0\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"申请时间：\"+data.createDate+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t</p>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"\t</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"</a>\";\r\n");
      out.write("    \t\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\t//报销\r\n");
      out.write("    \t\t\t\t\t\tht = \"<div class=\\\"dropdown-divider\\\"></div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<a class=\\\"dropdown-item preview-item\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-thumbnail\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-icon bg-primary\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"\t<i class=\\\"mdi mdi-food\\\"></i>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<div class=\\\"preview-item-content d-flex align-items-start flex-column justify-content-center\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t<h6 class=\\\"preview-subject font-weight-normal mb-1\\\">\"+data.addresserName+\"申请工作报销</h6>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t<p class=\\\"text-gray mb-0\\\">\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"申请时间：\"+data.createDate+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"\t</p>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"\t</div>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"</a>\";\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t$(\"#cn_message\").append(ht);\r\n");
      out.write("    \t\t\t\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t\tif(count==0){\r\n");
      out.write("    \t\t\t$(\"#cn_message\").html(\"<div class=\\\"dropdown-divider\\\"></div>\"+\r\n");
      out.write("    \t\t\t\t\t\"<a class=\\\"dropdown-item preview-item\\\">\"+\r\n");
      out.write("    \t\t\t\t\t\"<div class=\\\"preview-thumbnail\\\">\"+\r\n");
      out.write("    \t\t\t\t\t\"</div>\"+\r\n");
      out.write("    \t\t\t\t\t\"<div class=\\\"preview-item-content d-flex align-items-start flex-column justify-content-center\\\">\"+\r\n");
      out.write("    \t\t\t\t\t\"\t<h6 class=\\\"preview-subject font-weight-normal mb-1\\\"></h6>\"+\r\n");
      out.write("    \t\t\t\t\t\"\t<p class=\\\"text-gray mb-0\\\">\"+\r\n");
      out.write("    \t\t\t\t\t\"\t\t暂无新信息\"+\r\n");
      out.write("    \t\t\t\t\t\"\t</p>\"+\r\n");
      out.write("    \t\t\t\t\"\t</div>\"+\r\n");
      out.write("    \t\t\t\t\"</a>\");\r\n");
      out.write("    \t\t\t$(\"#cn_msg\").hide();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t},\"json\");   \r\n");
      out.write("   \t}\r\n");
      out.write("    function Sw(site,code,bId){\r\n");
      out.write("    \t\r\n");
      out.write("    \tif(site==1){\r\n");
      out.write("    \t\tif(code==2){\r\n");
      out.write("    \t\t\t$.post(\"/jboa/leave/updateMessageajax\",{\"bizId\":bId,\"addressees_id\":");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("},function(ret){\r\n");
      out.write("    \t\t\t\t\r\n");
      out.write("    \t\t\t});\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\tsetTimeout(function(){\r\n");
      out.write("        \t\twindow.location=\"/jboa/leave/queryLeave?pageNum=1&positionid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.position.positionid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&departmentid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&employeeid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("        \t},500);\r\n");
      out.write("    \t}else if(site==2){\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    } \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
