/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-12-07 10:19:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.show;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class leave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<title>申请假期</title>\r\n");
      out.write("\t\t<!-- plugins:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/iconfonts/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- inject:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../css/style.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../../../../images/favicon.png\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/css/laydate.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/jboa/css/defalut/laydate.css\" />\r\n");
      out.write("\t\t<script src=\"/jboa/js/laydate.js\"></script>\r\n");
      out.write("\t\t<style type=\"text/css\">\n");
      out.write("\t\t\ttr td{\r\n");
      out.write("\t\t\t\tpadding: 5px;\r\n");
      out.write("\t\t\t}body{\r\n");
      out.write("\t\t\t\tpadding: 10px;width: 1000px;\r\n");
      out.write("\t\t\t\tbackground: #f2edf3;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.laydate-icon{border:1px solid #ccc; background:url(/jboa/images/icon.png) 250px no-repeat;}\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style=\"padding: 10px;width: 1000px;\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"page-header border-bottom\" style=\"padding-bottom: 5px;\">\r\n");
      out.write("\t\t\t<h3 class=\"page-title\">\r\n");
      out.write("              <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\r\n");
      out.write("                <i class=\"mdi mdi-run\"></i>                 \r\n");
      out.write("              </span>\r\n");
      out.write("              \t请假申请\r\n");
      out.write("           </h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t<form action=\"/jboa/leave/addleave\" method=\"post\">\r\n");
      out.write("\t\t<table class=\"table\" width=\"100%\" style=\"text-align:center;border-color:#b66dff ;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\"><h3 class=\"font-weight-bold\">请假详情</h3></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  class=\"font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t姓名\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"createman\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.employeeid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td  class=\"font-weight-bold\">部门</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"departmentid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.department.departmentid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  class=\"font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t开始时间 <span style=\"color: red;\">*</span>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"starttime\" placeholder=\"开始时间\" class=\"laydate-icon form-control\" style=\"text-align: center;font-size: 16px;height: 40px;padding: 5px;\" id=\"start\"></td>\r\n");
      out.write("\t\t\t\t\t<td class=\"font-weight-bold\">结束时间 <span style=\"color: red;\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"endtime\" placeholder=\" 结束时间\" class=\"laydate-icon form-control\" style=\"text-align: center;font-size: 16px;height: 40px;padding: 5px;\" id=\"end\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"nextdealman\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emp.pid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  class=\"font-weight-bold\">请假日期</td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" style=\"text-align: center;\"><input type=\"hidden\" name=\"totalcount\"> <span id=\"day\"></span>天</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td  class=\"font-weight-bold\">请假事由 <span style=\"color: red;\">*</span></td>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\" style=\"text-align: center;\">\r\n");
      out.write("                      <textarea class=\"form-control\" id=\"exampleTextarea1\" rows=\"4\" name=\"event\"></textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-gradient-primary mr-2\">提交</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-light\">返回</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/jboa/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("\t\t<script src=\"/jboa/js/laydate/laydate.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("        //日期范围限制\r\n");
      out.write("          var start = laydate.render({\r\n");
      out.write("        \t  elem: '#start',\r\n");
      out.write("        \t  min:0,\r\n");
      out.write("        \t  trigger: 'click',\r\n");
      out.write("        \t  type:\"datetime\",\r\n");
      out.write("        \t  format:\"yyyy-MM-dd HH:mm:ss\",\r\n");
      out.write("        \t  theme: 'molv',\r\n");
      out.write("        \t  calendar: true,\r\n");
      out.write("        \t  value:new Date(),\r\n");
      out.write("        \t  done:function(value,dates){\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t  end.config.min ={\r\n");
      out.write("                          year:dates.year, \r\n");
      out.write("                          month:dates.month-1,\r\n");
      out.write("                          date: dates.date+1, \r\n");
      out.write("                          hours: 0, \r\n");
      out.write("                          minutes: 0, \r\n");
      out.write("                          seconds : 0\r\n");
      out.write("                 };\r\n");
      out.write("        \t  }\r\n");
      out.write("        \t});\r\n");
      out.write("        var end = laydate.render({\r\n");
      out.write("      \t  elem: '#end',\r\n");
      out.write("      \t  min:1,\r\n");
      out.write("      \t  trigger: 'click',\r\n");
      out.write("      \t  type:\"datetime\",\r\n");
      out.write("      \ttheme: 'molv',\r\n");
      out.write("      \tbtns: ['clear', 'confirm'],\r\n");
      out.write("      \t  format:\"yyyy-MM-dd HH:mm:ss\",\r\n");
      out.write("      \t  calendar: true,\r\n");
      out.write("      \t  done: function(value, date, endDate){\r\n");
      out.write("      \t\t   var startTime=$(\"#start\").val();\r\n");
      out.write("      \t    \tvar endTime=value;\r\n");
      out.write("      \t        if(startTime!=\"\"){\r\n");
      out.write("      \t       \t var time1 = Date.parse(new Date(startTime));\r\n");
      out.write("      \t\t\t\t var time2 = Date.parse(new Date(endTime));\r\n");
      out.write("      \t\t\t\t var count = Math.abs(parseInt((time2 - time1)/1000/3600/24));\r\n");
      out.write("      \t\t   \t\t\t\t\t  count++;\r\n");
      out.write("      \t\t\t\t\t  $(\"#day\").text(count);\r\n");
      out.write("      \t\t\t\t\t  $(\"[name=totalcount]\").val(count);\r\n");
      out.write("      \t\t\t\t\t  }\r\n");
      out.write("      \t        \r\n");
      out.write("     \t\t\t \r\n");
      out.write("            }\r\n");
      out.write("       \r\n");
      out.write("    \t});\r\n");
      out.write("        \r\n");
      out.write("     \r\n");
      out.write("        \r\n");
      out.write("   </script>\r\n");
      out.write("   \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
