/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-12-03 00:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.show;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class yearlyStatistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <!-- Required meta tags -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <title>清泉办公管理系统</title>\r\n");
      out.write("<!-- plugins:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/iconfonts/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- inject:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../css/style.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../../../../images/favicon.png\" />\r\n");
      out.write("\t\t<!-- plugins:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/iconfonts/mdi/css/materialdesignicons.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../vendors/css/vendor.bundle.base.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<!-- inject:css -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"../../css/style.css\">\r\n");
      out.write("\t\t<!-- endinject -->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../../../../images/favicon.png\" />\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\ttr td{\r\n");
      out.write("\t\t\t\tpadding: 5px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\t\tpadding: 10px;width: 1000px;\r\n");
      out.write("\t\t\t\tbackground: #f2edf3;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"page-header border-bottom\" style=\"padding-bottom: 5px;\">\r\n");
      out.write("\t\t\t<h3 class=\"page-title\">\r\n");
      out.write("              <span class=\"page-title-icon bg-gradient-primary text-white mr-2\">\r\n");
      out.write("                <i class=\"mdi mdi-file-chart\"></i>                 \r\n");
      out.write("              </span>\r\n");
      out.write("              \t年度统计\r\n");
      out.write("           </h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-lg-12 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t               <div class=\"card\">\r\n");
      out.write("  \t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t                \t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t                \t\t<h5>年份:</h5>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t                \t\t<select class=\"form-control form-control-lg\" id=\"type\" style=\"font-size: 16px;padding: 5px;height: 30px;\">\r\n");
      out.write("\t\t\t\t                \t\t\t<option>请选择</option>\r\n");
      out.write("\t\t\t\t\t                      <option>2017</option>\r\n");
      out.write("\t\t\t\t\t                      <option>2018</option>\r\n");
      out.write("\t\t\t\t\t                      <option>2019</option>\r\n");
      out.write("\t\t\t\t\t                    </select>\r\n");
      out.write("\t\t\t\t                \t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t                    <button type=\"submit\" class=\"btn btn-gradient-primary mb-2\"  style=\"padding: 7px;height: 30px;\"><i class=\"mdi mdi-yeast\"></i> 查询 </button>\r\n");
      out.write("\t\t\t\t                  </form>\r\n");
      out.write("\t\t\t\t                  <table class=\"table table-striped table-bordered\" style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t                    <thead>\r\n");
      out.write("\t\t\t\t                      <tr>\r\n");
      out.write("\t\t\t\t                        <th>编号</th>\r\n");
      out.write("\t\t\t\t                        <th>总计</th>\r\n");
      out.write("\t\t\t\t                        <th>年份</th>\r\n");
      out.write("\t\t\t\t                        <th>操作</th>\r\n");
      out.write("\t\t\t\t                      </tr>\r\n");
      out.write("\t\t\t\t                    </thead>\r\n");
      out.write("\t\t\t\t                    <tbody>\r\n");
      out.write("\t\t\t\t                      <tr>\r\n");
      out.write("\t\t\t\t                        <td>1</td>\r\n");
      out.write("\t\t\t\t                        <td>￥16356.0</td>\r\n");
      out.write("\t\t\t\t                        <td>12月</td>\r\n");
      out.write("\t\t\t\t                        <td><a href=\"yearlyDetails.jsp\" title=\"查看\"><i class=\"mdi mdi-yeast\"></i></a></td>\r\n");
      out.write("\t\t\t\t                      </tr>\r\n");
      out.write("\t\t\t\t                      <tr>\r\n");
      out.write("\t\t\t\t                        <td>1</td>\r\n");
      out.write("\t\t\t\t                        <td>￥16356.0</td>\r\n");
      out.write("\t\t\t\t                        <td>11月</td>\r\n");
      out.write("\t\t\t\t                        <td><a href=\"yearlyDetails.jsp\" title=\"查看\"><i class=\"mdi mdi-yeast\"></i></a></td>\r\n");
      out.write("\t\t\t\t                      </tr>\r\n");
      out.write("\t\t\t\t                     \r\n");
      out.write("\t\t\t\t                    </tbody>\r\n");
      out.write("\t\t\t\t                    <tfoot>\r\n");
      out.write("\t\t\t\t                    \t <tr>\r\n");
      out.write("\t\t\t\t                        <td class=\"alert-warning font-weight-bold\">总计</td>\r\n");
      out.write("\t\t\t\t                        <td class=\"alert-warning font-weight-bold\">￥16356.0</td>\r\n");
      out.write("\t\t\t\t                        <td class=\"alert-warning\" colspan=\"3\"></td>\r\n");
      out.write("\t\t\t\t                      </tr>\r\n");
      out.write("\t\t\t\t                    </tfoot>\r\n");
      out.write("\t\t\t\t                  </table>\r\n");
      out.write("\t\t\t\t                    <div class=\"btn-group\" role=\"group\" aria-label=\"Basic example\" style=\"height: 35px;margin-left: 30%;text-align: center;margin-top: 20px;\">\r\n");
      out.write("\t\t                          <button type=\"button\" class=\"btn btn-info\" style=\"padding: 5px 10px;\">首页</button>\r\n");
      out.write("\t\t                          <button type=\"button\" class=\"btn btn-info\" style=\"padding: 5px 10px;\">上一页</button>\r\n");
      out.write("\t\t                          <blockquote class=\"blockquote\" style=\"margin: 0px;height: 37px;padding: 0px 20px;font-size: 14px;\">\r\n");
      out.write("\t\t                          \t\t 第 1 / 9 页\r\n");
      out.write("\t\t                          \t\t<br />   \r\n");
      out.write("\t\t                          \t\t55 条记录\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t\t\t\t\t\t</blockquote>\r\n");
      out.write("\t\t                          <button type=\"button\" class=\"btn btn-info\" style=\"padding: 5px 10px;\">下一页</button>\r\n");
      out.write("\t\t                          <button type=\"button\" class=\"btn btn-info\" style=\"padding: 5px 10px;\">尾页</button>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t                        </div>\r\n");
      out.write("\t\t\t\t               <h4 style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t                   \t\t<a href=\"\"><button type=\"button\" class=\"btn btn-gradient-primary mr-2\">查看柱状图</button></a>\r\n");
      out.write("\t\t\t\t\t                    <a href=\"\"><button type=\"button\" class=\"btn btn-gradient-info mr-2\">查看饼状图</button></a>\r\n");
      out.write("\t\t\t\t\t                    <a href=\"\"><button type=\"button\" class=\"btn btn-gradient-dark mr-2\">查看曲线图</button></a>\r\n");
      out.write("\t\t\t\t                </h4>\r\n");
      out.write("\t\t\t\t                \r\n");
      out.write("\t\t\t\t              </div>\r\n");
      out.write("\t\t\t\t              \r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12 grid-margin stretch-card\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <div class=\"card\">\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t<div class=\"card-body\" >\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"Chartjs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t             \t\t\t</div>\r\n");
      out.write("\t\t\t\t             </div>\r\n");
      out.write("\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t    <!-- container-scroller -->\r\n");
      out.write("\t\t\t\t\t  <!-- plugins:js -->\r\n");
      out.write("\t\t\t\t\t  <script src=\"../../js/ichart.1.2.1.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t  <!-- endinject -->\r\n");
      out.write("\t\t\t\t\t  <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t\tvar flow=[];\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i=0;i<4;i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tflow.push(Math.floor(Math.random()*(60000+((i%12)*5)))+10);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tvar data1 = [\r\n");
      out.write("\t\t\t\t\t\t\t         \t{\r\n");
      out.write("\t\t\t\t\t\t\t         \t\tname : '报销金额',\r\n");
      out.write("\t\t\t\t\t\t\t         \t\tvalue:flow,\r\n");
      out.write("\t\t\t\t\t\t\t         \t\tcolor:'#0d8ecf',\r\n");
      out.write("\t\t\t\t\t\t\t         \t\tline_width:2\r\n");
      out.write("\t\t\t\t\t\t\t         \t}\r\n");
      out.write("\t\t\t\t\t\t\t         ];\r\n");
      out.write("\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\tvar labels = [\"丁磊\",\"雷军\",\"刘某\",\"卢老爷\"];\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar line = new iChart.LineBasic2D({\r\n");
      out.write("\t\t\t\t\t\t\t\trender : 'Chartjs',//ID\r\n");
      out.write("\t\t\t\t\t\t\t\tdata: data1,\r\n");
      out.write("\t\t\t\t\t\t\t\talign:'center',\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation:true,\r\n");
      out.write("\t\t\t\t\t\t\t\tanimation_duration:1000,\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle : '曲线图',\r\n");
      out.write("\t\t\t\t\t\t\t\tsubtitle : '年度报销统计',\r\n");
      out.write("\t\t\t\t\t\t\t\tfootnote : '数据来源：财务部',\r\n");
      out.write("\t\t\t\t\t\t\t\twidth : 800,\r\n");
      out.write("\t\t\t\t\t\t\t\theight : 400,\r\n");
      out.write("\t\t\t\t\t\t\t\tsub_option:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsmooth : true,//平滑曲线\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpoint_size:10\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\ttip:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tshadow:true\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tlegend : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenable : false\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tcrosshair:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tline_color:'#62bce9'\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tcoordinate:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\twidth:600,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalid_width:500,\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:260,\r\n");
      out.write("\t\t\t\t\t\t\t\t\taxis:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcolor:'#9f9f9f',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth:[0,0,2,2]\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgrids:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvertical:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tway:'share_alike',\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t\tvalue:12\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\tscale:[{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t position:'left',\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t start_scale:0,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t end_scale:100000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t scale_space:10000,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t scale_size:2,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t scale_color:'#9f9f9f'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t position:'bottom',\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t labels:labels\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}]\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t//开始画图\r\n");
      out.write("\t\t\t\t\t\tline.draw();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</body>\r\n");
      out.write("\t\t\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
